language: node_js
branches:
  only:
    - gh-pages
    - /.*/
node_js:
  - '8'
script:
  - node generateData.js
  - export TRAVIS_COMMIT_BUILD="$(cat .build_status)"
  - if [ "$TRAVIS_COMMIT_BUILD" = "continue" ]; then chmod +x .travis/push.sh  ; else echo "do build? $TRAVIS_COMMIT_BUILD" ; fi
  - if [ "$TRAVIS_COMMIT_BUILD" = "continue" ]; then ./.travis/push.sh  ; fi

env:
  global:
    secure: UsPtcGaCpmW4kvSqz65+VJEBFVoigK0g06hEdAVZhtyqBaCBwuOy8rysgjJ6WCC/HDC9ITsOIFN2LC0j0sXTRZGw5WBBR6f6x1XwfPN1zWGZ8x2647dsBoc5rxXGfXdE9IQsr33BDURpPakeHra6QJQKKqGYwaJZp9DSNuNkd/6oNjuJJ9P5AseB8xudkJCxA0EbnWVek3Tc1Q9zhJ0lUDYUZpRxuMShUERj3/YnIn+5DWhl3gYT/e1r3kIDOIPcBbKGDeJV4fwlx5953BfTiP0zUcnGgayMXY7qaog46KRR6PpdF0wN86c8y6LVR3TLJRYFGrsh2l+QA7oLRY4Vtm9d7tJE999DICq8ppkKroVE1WwLkUyaEdUcXoWcQrYRPfz0sTXuw6bpEyGde+Rgn38Z2j3vWWARHN/397KG2n9M0Gh4a073H9h2lCZZT0kLVNGIQBJmSwSJzBtjHItYidXb71Zl6ORwQIEXXzdOwCGpLS6FXotWB51p+20fXrU/Wd9TZURiBz6zfkvn+HTKm+Xm5qVvh+wBErBjFe4ielIRu5qmVdzwtsvq9XuVzVMKmgGoLjonPrs+to96Bqi9nOxEePeux3CDV9eRujgHvOjm7cdEagX6BrgTytrUS3dHWkZXta45j0Yr+byUsUwsXg/aJ/J75SrRCWOlqA+SveU=
